### ISSUE TITLE
Cannot navigate back to Landscape from BTC wallet on Port

### ISSUE THREAD

**Issue by bioy-casares** [urbit/bitcoin-wallet#23] opened 2021-05-28 21:57 UTC
Cannot navigate back to Landscape from BTC wallet when using Port.  Port does not offer a URL bar where you could clip the  "/~btc" off the end of the URL. Neither is there an (X) button to exit Bitcoin wallet.  Launch Bitcoin Wallet on Port to reproduce.

**Comment by urcades** [comment] 2021-06-03 01:20
Duplicate of #9 , but noted, and fully acknowledged

**Closed by urcades** 2021-06-03 01:20 UTC
